oa3_spec: ./openapi/openapi_internal_v1.json # If start with http the file would be downloaded from the internet
name: opex_pagopa-debt-position-internal-v1
location: West Europe
timespan: 5m # Default, a number or a timespan https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/scalar-data-types/timespan
data_source: /subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-api-rg/providers/Microsoft.ApiManagement/service/pagopa-p-apim
resource_type: api-management
overrides:
  base_path: "/gpd/api/v1"
  hosts: # Use these hosts instead of those inside the OpenApi spec
    - api.platform.pagopa.it
  endpoints:
    GET /organizations/{organizationfiscalcode}/paymentoptions/{nav}:
      response_time_threshold: 5
    POST /organizations/{organizationfiscalcode}/paymentoptions/{nav}/pay:
      response_time_threshold: 5
    POST /organizations/{organizationfiscalcode}/paymentoptions/{iuv}/transfers/{transferid}/report:
      response_time_threshold: 5
